services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  lab1-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/weather_db
      - SPRING_DATASOURCE_USERNAME=weather_user
      - SPRING_DATASOURCE_PASSWORD=weather_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    env_file:
      - src/main/resources/env.properties
    depends_on:
      - db

volumes:
  pgdata: