spring.application.name=lab1-api
server.port=8080

# ??????? ?????????? env.properties ???? (?????? ? Spring Boot 2.4+)
spring.config.import=optional:classpath:env.properties


api.openweather.url=https://api.openweathermap.org/data/2.5/weather

logging.charset.console=UTF-8