spring.application.name=lab1-api
server.port=8080

api.openweather.url=https://api.openweathermap.org/data/2.5/weather
api.currency.url=https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json

logging.charset.console=UTF-8